the-difference-engine/rescue-leftover-cuisine2

- docs/pull_request_template.md
Ticket #17 
Adding a pull request template to display on all future pull request descriptions.
> Create pr template

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
* [X ] I have documented all new functionality
> Add devise gem

- frontend/src/index.html
- frontend/src/styles/style.css
#15 
add postCss boilerplate typography color pallete
> postCss boilerplate typography color pallete issue15

- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20180807014553_devise_create_users.rb
- db/schema.rb
Problem: A visitor should be able to create an account, sign out, login, change password with partial functionality & delete account
The commands we ran to download package components:
```
rails generate devise User #devise user model that includes keys such as a user's email, account creation timestamp and encrypted password
rails generate devise :views #UI for core functionality, which includes messages and fields for sign up 
```
The code we included from Devise to test functionality:
```
<% if user_signed_in? %>
<li><%= link_to current_user.email, edit_user_registration_path %></li>
<li class="nav-item active"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
<% else %>
<li class="nav-item active"><%= link_to "Sign Up", new_user_registration_path %></li> …
```
> enabling visitors to create & manage accounts

- frontend/src/styles/style.css
#67 
Changed postCSS color variables to regular CSS variables
* [N/A] I have documented all new functionality
* [N/A] I have screenshotted new UI changes and attached them to this PR
> changed postCSS color variables to regular CSS variables

- README.md
This removes a now-unnecessary section on initial setup, and replaces it with a "nuclear option" section on resetting Docker.
> Updated environment setup instructions

- frontend/package.json
- frontend/public/index.html
- frontend/src/App.js
- frontend/src/common/Footer.js
add footer with copyright, design by, social icons with links
> add footer

- README.md
After discussion, we think this will be a better structure.
> Project directory structure revisited

- frontend/src/App.js
- frontend/src/containers/Homepage/Homepage.js
Due to my missing it, we've ended up with a couple components on App.js that shouldn't be there, which is causing those components to appear on every page. This is a little hilarious, but most annoying when you're trying to work on styling. This fixes that by moving these components to the Homepage.
Sorry to step on your toes, @mglavey, just wanted to get this out sooner than later. Tagging you and @mareann in as reviewers since y'all are working on this page.
> Move recipe list and bottom signup components to homepage

- frontend/src/components/MainSearch/MainSearch.css
Main search bar - move text to left
-  Add shadow 
* [x ] I have documented all new functionality
* [x ] I have screenshotted new UI changes and attached them to this PR
> search text is now left; text shadow

- frontend/src/components/BottomSignUp/BottomSignUp.css
- frontend/src/components/BottomSignUp/BottomSignUp.js
- frontend/src/components/Footer/Footer.css
- frontend/src/components/Footer/Footer.js
- frontend/src/components/RecipeCard/RecipeCard.css
- frontend/src/components/RecipeCard/RecipeCard.js
- frontend/src/components/RecipeSearchList/RecipeSearchList.js
Just fixing a few small tweaks in advance of the demo.
> Prevent style collisions and make necessary tweaks

- config/database.yml
Need to leverage DATABASE_URL in Heroku.
> Set up the database in production

- app/controllers/api/v1/recipe_controller.rb
- app/models/recipe.rb
* [ x ] I have documented all new functionality
* [ x ] I have screenshotted new UI changes and attached them to this PR
> fuzzy search implemented

- frontend/src/components/Footer/Footer.js
* [ x ] I have documented all new functionality
* [ x ] I have screenshotted new UI changes and attached them to this PR
> fixed spacing in footer

- frontend/src/components/Header/Header.js
- frontend/src/components/SearchBar/SearchBar.css
- frontend/src/components/SearchBar/SearchBar.js
- frontend/src/containers/AdminPanel/AdminPanel.js
- frontend/src/containers/CreateRecipe/CreateRecipe.js
- frontend/src/containers/Homepage/Homepage.js
Added search bar to the header. Only renders in the header on certain pages (not on main page and not on signup/login page)
No search bar:
Search bar:
> Add search bar to header

- app/models/recipe.rb
- app/models/user.rb
228
This fixes a 500 error on the admin page.
> Add back recipe belongs_to user assoc

- frontend/scripts/lint.sh
182
There was a bug in my linting script that allowed it to pass even when errors were detected. This fixes that bug.
> Prevent invalid linter passes

- .env.example
- .gitignore
- README.md
We've had some confusion around some of the environment variable mess required to enable Devise to function correctly, so I added some material to the readme. I also fixed a few small errors and expanded a couple sections to provide a better experience for new folks.
> Add an example .env file & update readme

- frontend/src/components/MainSearch/MainSearch.js
- frontend/src/components/RecipeSearchList/RecipeSearchList.js
- frontend/src/containers/Homepage/Homepage.js
I added some functionality in Homepage container and MainSearch component fixing the scrolling from search bar to the RecepeListSearch.
https://github.com/the-difference-engine/rescue-leftover-cuisine2/issues/330
> i added scrolling behavior in homepage.js

- frontend/package.json
> Add script for running and opening coverage

- frontend/package.json
> Remove the port 5000 thing from npm start

- frontend/src/components/EditRecipe/EditRecipeForm.js
- frontend/src/components/Header/Header.js
- frontend/src/containers/Homepage/Homepage.js
- frontend/src/containers/ProfilePage/ProfilePage.js
1.  If on the home page, clicking Browse Recipes button it jumps to where the recipes are listed
2. If anywhere else in the app, clicking Browse Recipes button it takes the user to the home page
> create functionality for Browse Recipes

- db/seeds.rb
I added some tags for a few more recipes in the seed file
> added some tags for recipes to the seed file

- db/migrate/20191115015725_remove_meal_from_recipes.rb
- db/schema.rb
- db/seeds.rb
- frontend/src/components/RecipeCard/RecipeCard.css
- frontend/src/components/RecipeCard/RecipeCard.js
- frontend/src/containers/ProfilePage/ProfilePage.js
I removed the meal lozenge from the recipe tiles
> remove the meal lozenge from the recipe tiles

- frontend/src/containers/RecipePage/Recipe.js
1. Admin can see edit/delete buttons for all recipes.
> if user is an admin edit delete buttons will be on all recipes

- frontend/src/containers/RecipePage/Recipe.js
Removed the unused Delete button from recipe pages.
> Took out the Delete button on recipe pages

- frontend/src/containers/Homepage/Homepage.js
1. Deleted period from the sentence on a home page
> punctuation fix

- frontend/src/components/CreateRecipeForm/CreateRecipeForm.js
1. Recipe page and card didn't have an icon with difficulty level.
> uppercased options of difficulty level to fix a bug

- frontend/src/containers/AdminPanel/AdminPanel.js
1. removed Add Recipe button from admin dashboard
> deleted button

- app/controllers/api/v1/recipes_controller.rb
- app/controllers/api/v1/registrations_controller.rb
- app/controllers/api/v1/users_controller.rb
- db/migrate/20200128013706_alter_recipes_photos_type.rb
- db/schema.rb
- db/seeds.rb
- frontend/src/components/CreateRecipeForm/CreateDirections/CreateDirections.js
- frontend/src/components/CreateRecipeForm/CreateDirections/CreateDirections.scss
- frontend/src/components/CreateRecipeForm/CreateRecipeForm.js
- frontend/src/components/CreateRecipeForm/CreateRecipeForm.scss
- frontend/src/components/CreateRecipeForm/Ingredients/Ingredients.js
- frontend/src/components/RecipeCard/RecipeCard.js
- frontend/src/components/UserProfilePanels/UserInfo.js
- frontend/src/components/UserProfilePanels/UserInfo.scss
- frontend/src/containers/RecipePage/Recipe.js
- frontend/src/lib/apiClient.js
- lib/image_uploader.rb
Closes #335 
Adds image upload capability for profile photo and recipe image (on create and edit).
It is not beautiful right now, but it works. The profile photo one looks a little prettier (but can result in some weird ovoid shapes if you give it a tall or wide image). The recipe photo is a little more standardized size-wise, but the uploader is not.. immaculately styled. I figure we can come back to that.
It's also fairly rudimentary. It'll stop people from uploading things that aren't images, and it'll blow up if they try to upload anything too huge. I'll try to come back in later this week to sand down some of the rough edges.
> Image upload

- app/controllers/api/v1/recipes_controller.rb
Pagination is broken on the user page
> Only paginate recipes when there is a page param
